### ISSUE TITLE
Crashes due to not enough colours assigned to multiple structural_category(/ies)

### ISSUE THREAD

**Issue by andredsim** [LRGASP/lrgasp-challenge-3-evaluation#1]
Some outputs had multiple structural categories which could cause crashes on lines 106 and 122. Below is how I handled it but it does change the plot since it now shows 2 or more colours.

`  scale_fill_manual(values=seq_along(unique(sqanti_data[,'structural_category'])))+`

**Comment by FJPardoPalacios** [comment]
Hi Andre, 

I just checked the code. Are you running this script using manatee data? Which reference file are you using as "reference"?

I'm asking because for Challenge 3 the annotation file that should be provided as reference is the one that just contains information about spike-ins. In consequence, all the isoforms (except for those mapping to the spike-ins chromosomes, which are not included in `sqanti_data`) must be catalogued as "Intergenic".  I'm wondering why you have several structural categories...

Fran

**Comment by andredsim** [comment]
Hi Fran,

The particular sample I found this in was for the ES mouse data. I used "lrgasp_sirvs4.gtf" as the gtf file which I aquired from the LRGASP website. Is this the correct one? This is the command I run (paths removed for clarity).

python sqanti3_lrgasp.challenge3.py models_stringtie2_conservative.fasta lrgasp_sirvs4.gtf lrgasp_grcm39_sirvs.fasta --experiment_json experiment.json --entry_json entry.json -c ES_rep1_illuminaSJ.out.tab -d submission_test -o submission_test

If it helps the structural categories that are found are Intergenic (21821) and FSM (15). I am guessing these 15 FSM shouldn't be in the sqanti_data so I am likely running the evaluation wrong. 

Thanks!

**Comment by FJPardoPalacios** [comment]
Hi Andre,

Okey, my bad. There are a few differences about the spike-ins used with manatee samples and mouse samples and that was causing the error. 

Let me fix this and I'll come back to you when it is ready.
Thanks!

Fran

**Comment by FJPardoPalacios** [comment]
Hi Andre,

It should be fixed now. It should choose a different "ground truth" for SIRV evaluation depending on the specie defined in the experiment JSON file.

Please, try to run it and, if everything is in place, we can close the issue.

Bests
Fran

**Comment by andredsim** [comment]
Hi Fran,
I tested the new version on the same data that it failed on last time and it worked. 
Thanks,
Andre
